entrypoint: sh -c "mkdir -p tmp/pids && bundle exec rails server -p $PORT"
runtime: ruby
env: flex

runtime_config:
    operating_system: "ubuntu22"

env_variables:
  SECRET_KEY_BASE: Rails.application.credentials.secret_key_base